FROM python:3.8-slim

RUN pip install --upgrade pip
RUN pip3 install numpy \
kafka-python \
termcolor

ADD ./tweetoscope/Hawks_processes Hawks_processes
ADD ./tweetoscope_2021_10/predictor.py .

CMD python3 predictor.py --broker-list kafka-service:9092

