FROM python:3.8-slim

### Librairies installations ###

RUN pip install --upgrade pip
RUN pip3 install numpy \
scipy \
matplotlib \
pandas \
seaborn \
kafka-python \
termcolor

### Adding files ###
WORKDIR Pipeline_ai
ADD estimator.py .
ADD Hawks_processes /Hawks_processes
ADD logger.py .

### Running command ###
CMD python3 estimator.py --broker-list kafka-service:9092

