FROM python:3.8-slim

### Libraries Installation ###
RUN pip install --upgrade pip
RUN pip install numpy \
scipy \
matplotlib \
pandas \
seaborn \
kafka-python \
termcolor
RUN pip install scikit-learn as sklearn 

### Adding files ###
ADD ./Pipeline_ai/Hawks_processes Hawks_processes
ADD ./Pipeline_ai/predictor.py .
ADD Pipeline_ai/logger.py .

### Running command ###
CMD python3 predictor.py --broker-list kafka-service:9092

