FROM python:3.8-slim

### Libraries Installation ###
RUN pip install --upgrade pip
RUN pip3 install numpy \
kafka-python \
termcolor

### Adding files ###
ADD ./Pipeline_ai/Hawks_processes Hawks_processes
ADD ./Pipeline_ai/predictor.py .

### Running command ###
CMD python3 predictor.py --broker-list kafka-service:9092

