
FROM ubuntu	

### Libraries Installation ###
RUN apt-get update
RUN apt-get install -y wget 
RUN apt-get install -y openjdk-8-jdk

### Get kafka ###

RUN wget https://archive.apache.org/dist/kafka/2.4.1/kafka_2.13-2.4.1.tgz
RUN tar zxvf kafka_2.13-2.4.1.tgz 
ENV KAFKA_PATH=./kafka_2.13-2.4.1


ADD ./tweetoscope/kafka.sh .
RUN chmod +x kafka.sh
ADD ./tweetoscope/server.properties .
ADD ./tweetoscope/zookeeper.properties .

# CMD ./kafka-2.4.1-src/gradlew jar -PscalaVersion=2.12.10

RUN /kafka.sh start --zooconfig zookeeper.properties --serverconfig server.properties 
