FROM ubuntu

### Libraries Installation ###
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt install -y build-essential pkg-config
RUN apt-get install -y cmake 
RUN apt-get install -y libboost-all-dev 
RUN apt-get install -y g++
RUN apt-get install -y gcc
RUN apt-get install -y librdkafka-dev
RUN apt-get install -y git 
RUN apt-get install libpthread-stubs0-dev
RUN apt-get install libssl-dev -y

### cppkafka Installation ###
RUN git clone https://github.com/mfontanini/cppkafka
RUN cd cppkafka;mkdir build;cd build;cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=64;make -j;make install;cd ../..

### Gaml Installation ###
RUN git clone https://github.com/HerveFrezza-Buet/gaml
RUN cd gaml; mkdir -p gaml/build;cd gaml/build;cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=64;make -j;make install;cd ../../..

ENV PKG_CONFIG_PATH=/gaml/gaml/build
### Copying files ###
COPY ./Tweet_collection/Tweet_Generator/news-index.csv .
ADD ./Tweet_collection/Tweet_Generator/news-data.csv . 
ADD ./Tweet_collection/Tweet_Generator/params.config .
ADD ./Tweet_collection/Tweet_Generator/tweetoscopeGenerator.hpp .
ADD ./Tweet_collection/Tweet_Generator/tweet-generator.cpp .

### Running command ###
RUN g++ -o tweet-generator -O3 -Wall -std=c++17 tweet-generator.cpp `pkg-config --libs --cflags gaml cppkafka` -lpthread
CMD ./tweet-generator params.config






