FROM python:3.8-slim

### Librairies installations ###

RUN pip install --upgrade pip
RUN pip install numpy \
scipy \
matplotlib \
pandas \
seaborn \
kafka-python \
termcolor

### Adding files ###

COPY /Pipeline_ai/estimator.py .
COPY Pipeline_ai/Hawks_processes ./Hawks_processes
COPY Pipeline_ai/logger.py .

### Running command ###
CMD python3 estimator.py --broker-list kafka-service:9092

