FROM python:3.8-slim

### Libraries Installation ###
RUN pip install --upgrade pip
RUN pip3 install kafka-python \
termcolor

### Adding file ###
ADD Pipeline_ai/logger.py .

### Running command ###
CMD python3 logger.py --broker-list kafka-service:9092