FROM ubuntu

### Libraries Installation ###
RUN apt-get update
RUN apt-get install -y build-essential 
RUN apt-get install -y pkg-config
RUN apt-get install -y cmake 
RUN apt-get install -y libboost-all-dev 
RUN apt-get install -y g++
RUN apt-get install -y gcc
RUN apt-get install -y librdkafka-dev
RUN apt-get install -y git 
RUN apt-get install libpthread-stubs0-dev
RUN apt-get install libssl-dev -y

### cppkafka Installation ###
RUN git clone https://github.com/mfontanini/cppkafka
RUN cd cppkafka;mkdir build;cd build;cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=64;make -j;make install;cd ../..

### Gaml Installation ###
RUN git clone https://github.com/HerveFrezza-Buet/gaml
RUN cd gaml; mkdir -p gaml/build;cd gaml/build;cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=64;make -j;make install;cd ../../..
ENV PKG_CONFIG_PATH=/gaml/gaml/build

### Adding files ###
ADD /Tweet_collection/Tweet_Collector .
ADD /Tweet_collection/Tweet_Collector/collector.ini .

### Running command ###
RUN g++ -o tweet-collector Tweet_Collector/tweet_collector.cpp -O3 $(pkg-config --cflags --libs gaml) -lpthread -lcppkafka
CMD ./tweet-collector collector.ini







