stages :
    - build_image

kafka_build :
    stage: build_image

    image: docker:latest

    services: 
        - docker:dind
    script:
        - cd Build
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE/kafka -f Dockerfile.kafka  .
        - docker push $CI_REGISTRY_IMAGE/kafka
    only:
        changes:
            - Build/Dockerfile.kafka

generator_build :
    stage: build_image

    image: docker:latest

    services: 
        - docker:dind
    script:
        - cd Build
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE/generator -f Dockerfile.tweetgenerator  ../
        - docker push $CI_REGISTRY_IMAGE/generator
    only:
        changes:
            - Build/Dockerfile.tweetgenerator
            - Tweet_collection/Tweet_Generator/*


collector_build :
    stage: build_image

    image: docker:latest
    services: 
        - docker:dind
    script:
        - cd Build
        - docker build -t $CI_REGISTRY_IMAGE/collector -f Dockerfile.tweetcollector ../
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker push $CI_REGISTRY_IMAGE/collector
    only:
        changes :
          - Build/Dockerfile.tweetcollector
          - Tweet_collection/Tweet_Collector/*


estimator_build :
    stage: build_image

    image: docker:latest
    services: 
        - docker:dind
    script:
        - cd Build
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE/estimator -f Dockerfile.estimator ../
        - docker push $CI_REGISTRY_IMAGE/estimator
    only:
        changes :
          - Build/Dockerfile.estimator
          - Pipeline_ai/Hawks_processes/*
          - Pipeline_ai/estimator.py



predictor_build :
    stage: build_image

    image: docker:latest
    services: 
        - docker:dind
    script:
        - cd Build
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE/predictor -f Dockerfile.predictor ../
        - docker push $CI_REGISTRY_IMAGE/predictor
    only:
        changes :
          - Build/Dockerfile.predictor
          - Pipeline_ai/Hawks_processes/*
          - Pipeline_ai/utils/*
          - Pipeline_ai/predictor.py


learner_build :
    stage: build_image
    image: docker:latest

    services: 
        - docker:dind
    script:
        - cd Build
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE/learner -f Dockerfile.learner ../
        - docker push $CI_REGISTRY_IMAGE/learner
    only:
        changes:
          - Build/Dockerfile.learner
          - Pipeline_ai/Hawks_processes/*
          - Pipeline_ai/learner.py
    

logger_build :
    stage: build_image
    image: docker:latest

    services: 
        - docker:dind
    script:
        - cd Build
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE/logger -f Dockerfile.logger ../
        - docker push $CI_REGISTRY_IMAGE/logger
    only:
        changes:
          - Build/Dockerfile.logger
          - Pipeline_ai/logger.py

